# Generated by Django 5.0.1 on 2024-01-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("author", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                ("likes", models.IntegerField()),
                ("image", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "comment",
            },
        ),
    ]
